language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: ILLUMINATE_VERSION=6.0.*
    - php: 7.3
      env: ILLUMINATE_VERSION=6.0.*
    - php: 7.4snapshot
      env: ILLUMINATE_VERSION=6.0.*

before_install:
  - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update -v
  - composer require "illuminate/events:${ILLUMINATE_VERSION}" --no-update -v

install: composer update --prefer-source --no-interaction --dev -v

script: vendor/bin/phpunit --debug -c phpunit.xml --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
